name: Build and publish to npm
run-name: ${{ github.actor }} is deploying new version of the package 🚀

on:
  push:
    branches: ["main"]

jobs:
  Run-Linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/composite-actions/install-dependencies

      - name: Run linters
        run: |
          yarn lint

  Build-and-Publish:
    runs-on: ubuntu-latest
    needs: Run-Linters

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/composite-actions/install-dependencies

      - name: Build
        run: |
          yarn build

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: false
          access: public

