name: Check pull request
run-name: ${{ github.actor }} is checking his pull request 🚀

on:
  pull_request:
    branches: ["main"]

jobs:
  Run-Linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/composite-actions/install-dependencies

      - name: Run linters
        run: |
          yarn lint
